### ISSUE TITLE
Demo down

### ISSUE THREAD

**Issue by reedspool** [eeue56/servelm#3]
http://107.170.81.176/ doesn't resolve. Awesome stuff, thanks!

**Comment by gabriela-sartori** [comment]
Still down

**Comment by yngbldjr** [comment]
Is this project maintained?  It is a very interesting one, and one I would love to start using, but at the moment I am not confident that I can get management buy in unless the package is maintained.  Last Commit was Feb 23 - is that good cause the code is so solid, or is that because lack of ability to work on the project?  I ask with the hopes of being able to use this for a work project.  I love elm and the things that it can do, and I am hopeful for this or other projects like it to spread the elm language and ecosystem.  Thanks for all the hard work, I understand it is a labor of love!  Please take my comments as constructive as I am truly trying to be.

**Comment by fatso83** [comment]
@yngbldjr: why just not become the maintainer? Fork it and bring some lifeblood into it. If you look at the size of the project, this is very manageable to do:

``` shell
find src -type f | xargs cat |wc -l
   489
```

That is little more than a few classes here and there in most projects.

**Comment by eeue56** [comment]
@fatso83 Please don't encourage forking of my projects without understanding the context. This is out of date for Elm 0.17. It will not be updated. Server side elm is not designed to work this way.

**Comment by fatso83** [comment]
Well, at least my encouragement to <del>steal (weird choice of words for an open sourced MIT licensed project)</del> fork brought the biggest improvement to the state of the project in months: 8196d9af72795f1a45ebb1e42a6065f91d64b612 ;-)

Since your project is still being linked to from other places, folks totally new to the Elm ecosystem and culture have no way of knowing whether something is just abandoned or a dead end. So thanks for updating the README!

**Comment by eeue56** [comment]
Yes, sorry - but it can be damaging to new Elm users to suggest picking up this project when it is dead for complex reasons :) 

https://github.com/noredink/take-home#faq has a good section on this
